### ISSUE TITLE
Ponyfill instead of polyfill

### ISSUE THREAD

**Issue by ehmicky** [Sec-ant/readable-stream#2]
First of all, thank you so much for this package. This is solving one hard problem we're having with the `get-stream` package (https://github.com/sindresorhus/get-stream/issues/116). The package looks spec-compliant, well-written and thoroughly tested!

I've tried myself creating polyfills in the past ([for `error.cause`](https://github.com/ehmicky/error-cause-polyfill)), and I remember it to be hard!

Could there be a way to use this package as a ponyfill instead of a polyfill? More specifically, to be able to call the main function:

https://github.com/Sec-ant/readable-stream/blob/f03f38cfcbadf815b32611ef2489da31039c8ff3/src/asyncIteration.ts#L161-L184

But without setting `ReadableStream.prototype.values` and `ReadableStream.prototype[Symbol.asyncIterator]`? I understand those are only set when `undefined`, but this is still a side effect that some users (like us) might not need it.

Usually, this would require using two separate entrypoints in `package.json` ([example](https://github.com/ehmicky/error-cause-polyfill/blob/e6babe2fb05cb4886b3b627cf8d7e44cc67e7390/package.json#L5)) to differentiate polyfills and ponyfills.

I am happy to submit a PR, or help review it, whichever you prefer.

**Comment by Sec-ant** [comment]
Hey @ehmicky, I'm really glad this package is helpful.

Actually, the reason I initially created this package was due to the large size of [web-streams-polyfill](https://github.com/MattiasBuelens/web-streams-polyfill). I referenced its internal implementation to write this package, which is solely used to polyfill the `asyncIterable` functionality.

> Could there a way to use this package as a ponyfill instead of a polyfill?

When I was writing this package, I didn't have a comprehensive consideration for polyfill, but now I fully agree with you that we should provide users with a side-effect-free entry point.

> I am happy to submit a PR, or help review it, whichever you prefer.

Seeing this package being used in other projects has motivated me to keep it maintained. I'm now considering revisiting the project, updating some dev dependencies, setting up some tools for easy maintenance, reviewing the recent updates in `web-streams-polyfill` to find (maybe) obsolete code or  new edge cases, and also improving README.

I plan to refactor the package entry points like what I did in [my another BarcodeDetection API polyfill repo](https://github.com/Sec-ant/barcode-detector). I hope you don't mind my plan to first restructure this repository following my own approach, but I definitely welcome any kind of advice and code reviews during this process.

**Comment by ehmicky** [comment]
This sounds great! In the meantime, I'll use the following workaround:

```js
export const ponyfill = {};

const {prototype} = ReadableStream;

if (prototype[Symbol.asyncIterator] === undefined && prototype.values === undefined) {
	await import('@sec-ant/readable-stream');
	ponyfill.asyncIterator = prototype[Symbol.asyncIterator];
	delete prototype[Symbol.asyncIterator];
	delete prototype.values;
}
```

> I plan to refactor the package entry points like what I did in [my another BarcodeDetection API polyfill repo](https://github.com/Sec-ant/barcode-detector).

This looks great too :+1: 

If you need me on any PR or issue, please just tag @ehmicky, I'm happy to help!

You might have already looked at it, but another potential source of inspiration is the [Node.js implementation](https://github.com/nodejs/node/blob/b360532f1a38ac9a254187f3e2e90c3a91b66b2e/lib/internal/webstreams/readablestream.js#L460) for `Readable.prototype[Symbol.asyncIterator]`. From what I can tell, it's pretty similar, but you might find some small interesting bits.

**Comment by Sec-ant** [comment]
[v0.4.0](https://www.npmjs.com/package/@sec-ant/readable-stream/v/0.4.0) is published.

**Comment by Sec-ant** [comment]
Sorry I made a mistake in `package.json`, please use v0.4.1 😅

**Comment by ehmicky** [comment]
This works in our code. https://github.com/sindresorhus/get-stream/pull/128

Thanks again!
